# Generated by Django 6.0.2 on 2026-02-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmojiEffectConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(default='❄️', help_text='Emoji para el efecto decorativo', max_length=8)),
                ('opacity', models.FloatField(default=1.0, help_text='Opacidad del emoji (0.0 a 1.0)')),
            ],
            options={
                'verbose_name': 'Configuración de efecto emoji',
                'verbose_name_plural': 'Configuraciones de efecto emoji',
            },
        ),
    ]
