# Generated by Django 6.0.2 on 2026-02-18 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Carrito', 'verbose_name_plural': 'Carritos'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Ítem del carrito', 'verbose_name_plural': 'Ítems del carrito'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Imagen de producto', 'verbose_name_plural': 'Imágenes de productos'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['id'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
